baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "RLsquared"
theme = "hugo-bootstrap-premium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[params.theme]
    name = "journal"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    weight = 1
    name = "Home"
    url = "/"

[[menu.main]]
    weight = 5
    name = "People"
    url = "/people/"
    
[[menu.main]]
    weight = 10
    name = "Publications"
    url = "/publications/"

#[[menu.main]]
#    weight = 15
#    name = "Projects"
#    url = "/projects/"

[[menu.main]]
    weight = 20
    name = "Code"
    identifier = "code"
    url = "https://github.com/rlsquared"

[[menu.main]]
    parent = "code"
    weight = 20
    name = "GitHub"
    

[params]
    description = "Reinforcement Learning and Robustness Lab"

    #logoimage = "/img/logo-small.png"
    #BrandImage = "/img/logo-small.png"

    home = "home"

    showRightSidebar = false

    highlight = "default"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

